package src.rules
 import struct.CharacterData
import enumerate.State
import enumerate.Action
import comment.Message
import java.lang.Math


rule "p1"
when 
$p1:CharacterData($p1.playerNumber==true,$p1.isHitConfirm()==true)

$m:Message()
then   
$m.setOffence(1);

end

rule "p2"

when 
$p1:CharacterData($p1.playerNumber==false,$p1.isHitConfirm()==true)

$m:Message()
then   
$m.setOffence(0);

end

rule "air"

when 
$p1:CharacterData($p1.getState().toString().equals("AIR"))

$m:Message()

then   
$m.setState("air");

end

rule "corner"
when
$p1:CharacterData((Math.abs(480.0 - $p1.getCenterX())/480.0)>0.9||(Math.abs(480.0 - $p1.getCenterX())/480.0)<0.1)
$m:Message()
then
//System.out.println("corner");
$m.setCorner(true);
end

rule "relativeDistance"
when
$p1:CharacterData($p1.playerNumber==true)
$p2:CharacterData($p2.playerNumber==false)
then
end
rule "ult"
when CharacterData(hitCount>=1,action.toString().equals("STAND_D_DF_FA")||action.toString().equals("STAND_D_DF_FB")||action.toString().equals("STAND_F_D_DFA")||action.toString().equals("STAND_F_D_DFB")||action.toString().equals("STAND_D_DF_FC")||action.toString().equals("STAND_D_DB_BB"),$n:playerNumber,$action:action.toString())

$m:Message()  
then 
$m.setAction($action);
$m.setPlayerName($n);
$m.setUlt(true);
end
rule "lowhp"
when CharacterData(hp<=30,$n:playerNumber,$action:action.toString())
$m:Message()
then  
$m.setHp(true);
$m.setPlayerName($n);
$m.setAction($action);
end
rule "forjump"
no-loop

when  CharacterData(action.toString().equals("FOR_JUMP")||action.toString().equals("BACK_JUMP"),$n:playerNumber,$action:action.toString())
$m:Message()
then  
$m.setJump(true);
$m.setPlayerName($n);
$m.setAction($action);
end

rule "heavy"
when  CharacterData(hitCount>=1,action.toString().equals("STAND_FA")||action.toString().equals("CROUCH_FA")||action.toString().equals("STAND_FB")||action.toString().equals("CROUCH_FB"),$n:playerNumber,$action:action.toString())
$m:Message()
then  
$m.setHeavy(true);
$m.setPlayerName($n);
$m.setAction($action);
end

rule "lose"
when CharacterData(hp<=0)
$p1:CharacterData(hp>0,$n:playerNumber,$action:action.toString())
$m:Message()
then
$m.setPlayerName($n);
$m.setAction($action);
$m.setEnd(true);
end

rule "combo"
when 
CharacterData(hitCount>=3,$n:playerNumber,$action:action.toString())
$m:Message()
then  
$m.setCombo(true);
$m.setPlayerName($n);
$m.setAction($action);
end

rule "block"
when 
CharacterData(action.toString().equals("STAND_GUARD")||action.toString().equals("CROUCH_GUARD"),$n:playerNumber,$action:action.toString())
CharacterData(hitCount>=1)
$m:Message()
then  
$m.setBlock(true);
$m.setPlayerName($n);
$m.setAction($action);
end